import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from 'next/headers'
import AdminSidebar from '@/components/AdminSidebar'
import { createClient } from '@/lib/supabase/server'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  const requestHeaders = await headers()
  const nextUrl = requestHeaders.get('next-url') || ''
  const pathname = nextUrl.startsWith('http') ? new URL(nextUrl).pathname : nextUrl.split('?')[0]
  const hideSidebar = pathname === '/landing' || pathname.startsWith('/auth') || pathname.startsWith('/s/')
  const showSidebar = !!user && !hideSidebar

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body style={{ margin: 0, padding: 0, background: '#f8f8f7', minHeight: '100vh' }}>
        <div style={{ display: 'flex', minHeight: '100vh', background: '#f8f8f7' }}>
          <AdminSidebar visible={showSidebar} />
          <div style={{ flex: 1, background: '#f8f8f7', minHeight: '100vh' }} id="main-content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
